//! Bounded session delivery for server-generated production Recall completion.
//!
//! Authority: `Gravebound_Production_GDD_v1_Canonical.md` `DTH-010` and
//! `TECH-015`/`021`-`023`; `Gravebound_Content_Production_Spec_v1.md`
//! `CONT-HUB-001`/`002` and Hall `(32,42)` return authority;
//! `Gravebound_Development_Roadmap_v1.md` `GB-M03-03`/`08`; and accepted
//! `SPEC-CONFLICT-029`.
//!
//! Recall completion is generated by the character tick, not a second client
//! request. This bounded outbox transfers only an already committed publication
//! to the session writer. Saturation or transport loss cannot roll back the
//! terminal result; exact replay remains available from the actor/repository.

use protocol::{CharacterLocationSnapshot, ReliableEvent, ReliableEventFrame};
use thiserror::Error;
use tokio::sync::mpsc;

use crate::{
    CoreRecallTerminalTickOutcome, ProductionRecallExecutionError, ProductionRecallPublishedV1,
    ServerTransportError, send_server_reliable_event,
};

pub const CORE_RECALL_COMPLETION_OUTBOX_CAPACITY: usize = 8;

#[derive(Debug, Clone)]
pub struct CoreRecallCompletionOutbox {
    sender: mpsc::Sender<ProductionRecallPublishedV1>,
}

#[derive(Debug)]
pub struct CoreRecallCompletionInbox {
    receiver: mpsc::Receiver<ProductionRecallPublishedV1>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct CoreReliableSequence {
    last_sequence: u32,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CoreRecallCompletionDelivery {
    pub frame: ReliableEventFrame,
    pub hall: CharacterLocationSnapshot,
}

#[derive(Debug, Error)]
pub enum CoreRecallOutboxError {
    #[error("Recall completion publication is invalid")]
    InvalidPublication(#[source] ProductionRecallExecutionError),
    #[error("Recall completion outbox is saturated")]
    Saturated,
    #[error("Recall completion session is unavailable")]
    SessionUnavailable,
    #[error("Core reliable sequence is exhausted")]
    SequenceExhausted,
    #[error("server-initiated Recall delivery failed")]
    Transport(#[source] ServerTransportError),
}

#[must_use]
pub fn core_recall_completion_outbox() -> (CoreRecallCompletionOutbox, CoreRecallCompletionInbox) {
    let (sender, receiver) = mpsc::channel(CORE_RECALL_COMPLETION_OUTBOX_CAPACITY);
    (
        CoreRecallCompletionOutbox { sender },
        CoreRecallCompletionInbox { receiver },
    )
}

impl CoreRecallCompletionOutbox {
    /// Enqueues one committed Recall without blocking the authoritative tick.
    pub fn try_publish(
        &self,
        published: ProductionRecallPublishedV1,
    ) -> Result<(), CoreRecallOutboxError> {
        published
            .validate()
            .map_err(CoreRecallOutboxError::InvalidPublication)?;
        self.sender
            .try_send(published)
            .map_err(|error| match error {
                mpsc::error::TrySendError::Full(_) => CoreRecallOutboxError::Saturated,
                mpsc::error::TrySendError::Closed(_) => CoreRecallOutboxError::SessionUnavailable,
            })
    }

    /// Publishes only a committed Recall outcome; nonterminal and other-terminal outcomes remain
    /// with their owning tick executor.
    pub fn try_publish_outcome(
        &self,
        outcome: &CoreRecallTerminalTickOutcome,
    ) -> Result<bool, CoreRecallOutboxError> {
        match outcome {
            CoreRecallTerminalTickOutcome::RecallStored(published)
            | CoreRecallTerminalTickOutcome::RecallReplayed(published) => {
                self.try_publish(published.clone())?;
                Ok(true)
            }
            CoreRecallTerminalTickOutcome::NoTerminal
            | CoreRecallTerminalTickOutcome::OtherTerminalPrepared(_) => Ok(false),
        }
    }
}

impl CoreReliableSequence {
    #[must_use]
    pub const fn new() -> Self {
        Self { last_sequence: 0 }
    }

    #[must_use]
    pub const fn last_sequence(self) -> u32 {
        self.last_sequence
    }

    pub fn next_sequence(&mut self) -> Result<u32, CoreRecallOutboxError> {
        self.last_sequence = self
            .last_sequence
            .checked_add(1)
            .ok_or(CoreRecallOutboxError::SequenceExhausted)?;
        Ok(self.last_sequence)
    }

    fn frame(
        &mut self,
        server_tick: u64,
        event: ReliableEvent,
    ) -> Result<ReliableEventFrame, CoreRecallOutboxError> {
        let frame = ReliableEventFrame {
            sequence: self.next_sequence()?,
            server_tick,
            event,
        };
        frame.validate().map_err(|_| {
            CoreRecallOutboxError::InvalidPublication(
                ProductionRecallExecutionError::PublishedReceiptMismatch,
            )
        })?;
        Ok(frame)
    }
}

impl CoreRecallCompletionInbox {
    /// Sends the next committed completion on a server-initiated QUIC stream. `Ok(None)` means
    /// every producer handle has retired and no queued completion remains.
    pub async fn send_next(
        &mut self,
        connection: &quinn::Connection,
        sequence: &mut CoreReliableSequence,
    ) -> Result<Option<CoreRecallCompletionDelivery>, CoreRecallOutboxError> {
        let Some(published) = self.receiver.recv().await else {
            return Ok(None);
        };
        let server_tick = published
            .completion_tick()
            .map_err(CoreRecallOutboxError::InvalidPublication)?;
        let frame = sequence.frame(
            server_tick,
            ReliableEvent::RecallResult(Box::new(published.result.clone())),
        )?;
        send_server_reliable_event(connection, &frame)
            .await
            .map_err(CoreRecallOutboxError::Transport)?;
        Ok(Some(CoreRecallCompletionDelivery {
            frame,
            hall: published.hall,
        }))
    }
}

#[cfg(test)]
mod tests {
    use protocol::{
        CharacterLocation, RecallResultV1, RecallTerminalTriggerV1, SafeArrival,
        StoredRecallTerminalResultV1, TERMINAL_HALL_CONTENT_ID, TERMINAL_INVENTORY_SCHEMA_VERSION,
        TerminalVersionAdvanceV1, TerminalVersionVectorV1, WireText,
    };

    use super::*;

    fn published() -> ProductionRecallPublishedV1 {
        ProductionRecallPublishedV1 {
            result: RecallResultV1::Stored {
                schema_version: TERMINAL_INVENTORY_SCHEMA_VERSION,
                request_sequence: Some(7),
                replayed: false,
                result: Box::new(StoredRecallTerminalResultV1 {
                    character_id: [2; 16],
                    terminal_id: [3; 16],
                    result_hash: [4; 32],
                    trigger: RecallTerminalTriggerV1::Explicit,
                    committed_at_unix_millis: 50,
                    completion_tick: 112,
                    destination_content_id: WireText::new(TERMINAL_HALL_CONTENT_ID).unwrap(),
                    versions: TerminalVersionVectorV1 {
                        account: version(5, 5),
                        character: version(6, 7),
                        world: version(6, 7),
                        inventory: version(7, 8),
                        life_clock: version(8, 9),
                    },
                    stabilized_item_count: 0,
                    stabilized_items_digest: [5; 32],
                    destroyed_item_count: 0,
                    destroyed_items_digest: [6; 32],
                    destroyed_material_stack_count: 0,
                    destroyed_materials_digest: [7; 32],
                }),
            },
            hall: CharacterLocationSnapshot {
                character_id: [2; 16],
                character_version: 7,
                location: CharacterLocation::Safe {
                    location_id: WireText::new(TERMINAL_HALL_CONTENT_ID).unwrap(),
                    arrival: SafeArrival::HallDefault,
                },
            },
            explicit_client_tick: Some(8_000),
        }
    }

    const fn version(before: u64, after: u64) -> TerminalVersionAdvanceV1 {
        TerminalVersionAdvanceV1 { before, after }
    }

    #[test]
    fn outbox_is_bounded_nonblocking_and_validates_before_enqueue() {
        let (outbox, _inbox) = core_recall_completion_outbox();
        assert_eq!(CORE_RECALL_COMPLETION_OUTBOX_CAPACITY, 8);
        for _ in 0..CORE_RECALL_COMPLETION_OUTBOX_CAPACITY {
            outbox.try_publish(published()).unwrap();
        }
        assert!(matches!(
            outbox.try_publish(published()),
            Err(CoreRecallOutboxError::Saturated)
        ));

        let (outbox, _inbox) = core_recall_completion_outbox();
        let mut invalid = published();
        invalid.hall.character_version += 1;
        assert!(matches!(
            outbox.try_publish(invalid),
            Err(CoreRecallOutboxError::InvalidPublication(_))
        ));
        assert!(
            outbox
                .try_publish_outcome(&CoreRecallTerminalTickOutcome::RecallStored(published()))
                .unwrap()
        );

        let (outbox, inbox) = core_recall_completion_outbox();
        drop(inbox);
        assert!(matches!(
            outbox.try_publish(published()),
            Err(CoreRecallOutboxError::SessionUnavailable)
        ));
    }

    #[test]
    fn sequence_is_shared_across_request_responses_and_push_delivery() {
        let mut sequence = CoreReliableSequence::new();
        assert_eq!(sequence.next_sequence().unwrap(), 1);
        let pushed = sequence
            .frame(
                112,
                ReliableEvent::RecallResult(Box::new(published().result)),
            )
            .unwrap();
        assert_eq!(pushed.sequence, 2);
        assert_eq!(pushed.server_tick, 112);
        assert_eq!(sequence.last_sequence(), 2);

        let mut exhausted = CoreReliableSequence {
            last_sequence: u32::MAX,
        };
        assert!(matches!(
            exhausted.next_sequence(),
            Err(CoreRecallOutboxError::SequenceExhausted)
        ));
    }
}
